# [START swagger]
swagger: "2.0"
info:
  description: "Test google endpoints."
  title: "Endpoints Example"
  version: "1.0.0"
host: "test-api.endpoints.testing-ucic.cloud.goog"
x-google-endpoints:
  - name: "test-api.endpoints.testing-ucic.cloud.goog"
    target: "34.71.234.187"
    allowCors: true
# [END swagger]
consumes:
  - "application/json"
produces:
  - "application/json"
schemes:
  # Uncomment the next line if you configure SSL for this API.
  # - "https"
  - "http"
paths:
  "/commentaries":
    get:
      description: "Returns Hello World."
      operationId: "ListCommentaries"
      produces:
        - "application/json"
      responses:
        200:
          description: OK
      security:
        - api_key: []
securityDefinitions:
  # This section configures basic authentication with an API key.
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"